- hosts: '{{ hosts_name }}'
  tasks:       
        
    - name: is install tool
      shell: which npu-smi
      register: isInstalledTool
      ignore_errors: yes
      when: ansible_user_uid == 0

    - name: message
      debug:
        msg:
          - "npu-smi tool is not installed, please check it"
      when: 
        - ansible_user_uid == 0      
        - isInstalledTool.rc == 1

    - name: check health
      shell: npu-smi info|grep -E '910|710|310'|awk -F' ' '{print $5}'|grep -v '|'
      register: result_info
      when: 
        - ansible_user_uid == 0      
        - isInstalledTool.rc == 0

    - name: is everychip ok
      set_fact: NPUIssue=true
      when:
        - ansible_user_uid == 0      
        - isInstalledTool.rc == 0
        - result_info is defined
        - item != 'OK'
      loop: "{{result_info.stdout_lines}}"

    - name: message
      debug:
        msg:
          - "critical issue with NPU, please check it"
      failed_when: true
      when:
        - NPUIssue is defined

    - name: import firmware task
      import_tasks: task_firmware.yml
      when: ansible_user_uid == 0

    - name: message
      debug:
        msg:
        - "not support installing firmware by non-root user, please switch to root user"
      when: ansible_user_uid != 0
