- name: link hdf5 for ubuntu
  shell: ln -sf /usr/lib/`uname -m`-linux-gnu/libhdf5_serial.so /usr/lib/`uname -m`-linux-gnu/libhdf5.so
  when: ansible_pkg_mgr == 'apt'
  failed_when: false

- name: centos stat /usr/lib64/libhdf5.so
  stat:
    path: /usr/lib64/libhdf5.so
  register: centos_libhdf5
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
  failed_when: false

- name: link hdf5 for centos
  shell: ln -sf `find /usr/lib64/ -type f -name "libhdf5.so*"` /usr/lib64/libhdf5.so
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - not centos_libhdf5.stat.exists
  failed_when: false

- name: install tensorflow
  shell: python3 -m pip install tensorflow==2.4.1 --no-index --find-links {{ resources_dir }}/pylibs {{ pip_install_option }}
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib:{{ local_path }}/gcc7.3.0/lib64"
    CPATH: /usr/include/hdf5/include/:/usr/include/hdf5/lib/
  when: ansible_architecture == 'aarch64'
  register: install_tensorflow

- name: install tensorflow_cpu
  shell: python3 -m pip install tensorflow_cpu==2.4.1 --no-index --find-links {{ resources_dir }}/pylibs {{ pip_install_option }}
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib:{{ local_path }}/gcc7.3.0/lib64"
  when: ansible_architecture == 'x86_64'
