- hosts: '{{ hosts_name }}'

- name: install system dependencies
  import_playbook: ../install/install_sys_pkg.yml

- name: install python3.7.5
  import_playbook: ../install/install_python375.yml

- name: install driver and firmware
  import_playbook: ../install/install_npu.yml

- name: install nnrt
  import_playbook: ../install/install_nnrt.yml
  when: ansible_local.npu_info.scene == 'infer'

- name: install nnae
  import_playbook: ../install/install_nnae.yml
  when: ansible_local.npu_info.scene == 'train'

- name: install tfplugin
  import_playbook: ../install/install_tfplugin.yml

- name: install toolbox
  import_playbook: ../install/install_toolbox.yml

- name: install toolkit
  import_playbook: ../install/install_toolkit.yml

- name: install torch
  import_playbook: ../install/install_torch.yml

- name: install tensorflow
  import_playbook: ../install/install_tensorflow.yml

- name: install mindspore
  import_playbook: ../install/install_mindspore.yml
