- hosts: '{{ hosts_name }}'
  tasks:
    - name: find nnae package
      find:
        paths: "{{ resources_dir }}"
        recurse: no
        file_type: file
        use_regex: yes
        patterns: ".*nnae.*{{ ansible_architecture }}.run"
      register: nnae

    - name: add run permission for nnae
      file:
        path: "{{ nnae.files[0].path }}"
        mode: a+x
      when: nnae.matched > 0

    - name: install nnae
      shell: "{{ nnae.files[0].path }} --install --quiet --install-username={{ user }} --install-usergroup={{ group }}"
      register: nnae_result
      when: nnae.matched > 0
      failed_when: "'install success' not in nnae_result.stdout and 'already installed' not in nnae_result.stdout"

    - debug: var=nnae_result
