- name: upgrade pip
  shell: python3.7 -m pip install --upgrade pip --no-index --find-links {{ resources_dir }}/`uname -m`
  environment:
    PATH: /usr/local/python3.7.5/bin:{{ ansible_env.PATH }}
    LD_LIBRARY_PATH: /usr/local/python3.7.5/lib:/usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64:/usr/local/gcc7.3.0/lib64

- name: install torch
  shell: python3.7 -m pip install torch --no-index --find-links {{ resources_dir }}/`uname -m`
  environment:
    PATH: /usr/local/python3.7.5/bin:{{ ansible_env.PATH }}
    LD_LIBRARY_PATH: /usr/local/python3.7.5/lib:/usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64:/usr/local/gcc7.3.0/lib64

- name: install apex
  shell: python3.7 -m pip install apex --no-index --find-links {{ resources_dir }}/`uname -m`
  environment:
    PATH: /usr/local/python3.7.5/bin:{{ ansible_env.PATH }}
    LD_LIBRARY_PATH: /usr/local/python3.7.5/lib:/usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64:/usr/local/gcc7.3.0/lib64
